server: main.cpp ./threadpool/threadpool.hpp ./http_conn/http_conn.cpp ./http_conn/http_conn.h ./lock/locker.h ./log/log.cpp ./log/log.h ./log/block_queue.h 
	g++ -o server main.cpp ./threadpool/threadpool.hpp ./http_conn/http_conn.cpp ./http_conn/http_conn.h ./lock/locker.h ./log/log.cpp ./log/log.h -lpthread


clean:
	rm  -r server